VisitPush event type for Clinical Summary + some extensions
mdcollab/scala-redox pull request #27
Opened 2021-11-08 16:44 UTC by chennen-carbon

In order to use Redox as a query responder on the Carequality network, we need to push Clinical Summary data to their Data-on-Demand product via the `PatientPush` and `VisitPush` event types:

https://developer.redoxengine.com/data-models/ClinicalSummary.html#PatientPush
https://developer.redoxengine.com/data-models/ClinicalSummary.html#VisitPush

The `PatientPush` event type is already present in this SDK but `VisitPush` needs to be added.

Additionally, in order to use Redox to query for patients/organizations/documents on the Carequality network, we need a few extensions for the Meta object in the query datamodels.

2021-11-09 13:10 UTC, talha-sen-carbon requested changes
1 small change needed. Also, are you planning to update the version with this PR or not? If you plan to update it with this PR, you need to include the version change too. If not, thats okay. Though I think coupling the version change with the PR is better logically.

2021-11-09 13:10 UTC, talha-sen-carbon commented on src/main/scala/com/github/vitalsoftware/scalaredox/models/clinicalsummary/VisitPush.scala
> +object PatientPush extends RobustPrimitives
This needs to be VisitPush

2021-11-09 13:12 UTC, talha-sen-carbon commented on src/main/scala/com/github/vitalsoftware/scalaredox/models/clinicalsummary/VisitPush.scala
> +object PatientPush extends RobustPrimitives
```suggestion
object VisitPush extends RobustPrimitives
```

2021-11-10 09:46 UTC, atillacarbon reviewed
Should we add a test class `VisitPushTest.scala` like `ClinicalSummaryTest.scala` to test if we have created the data structure correctly? Or how we gonna test it?

2021-11-10 10:31 UTC, talha-sen-carbon approved these changes

2021-11-10 10:32 UTC, talha-sen-carbon reviewed
Currently, VisitPush is the same as PatientPush. Though I don't think it is necessary, it would be a nice touch.

2021-11-15 22:23 UTC, chennen-carbon commented
> Should we add a test class `VisitPushTest.scala` like `ClinicalSummaryTest.scala` to test if we have created the data structure correctly? Or how we gonna test it?

Nothing to test, really? It's just a case class with a regular JSON serializer.

2021-11-16 07:07 UTC, chennen-carbon commented
> Currently, VisitPush is the same as PatientPush. Though I don't think it is necessary, it would be a nice touch.

I'm not sure what change you're suggesting? VisitPush has (slightly) different properties than PatientPush, and was copied from Redox's dev docs online.

2021-11-16 08:27 UTC, atillacarbon commented
> > Should we add a test class `VisitPushTest.scala` like `ClinicalSummaryTest.scala` to test if we have created the data structure correctly? Or how we gonna test it?
> 
> Nothing to test, really? It's just a case class with a regular JSON serializer.

Gotcha! This is the opposite, we producing the json. I going to approve.
fyi: Some test failures.

2021-11-16 08:27 UTC, atillacarbon submitted a review, later dismissed

2021-11-16 17:16 UTC, talha-sen-carbon approved these changes
lgtm

2021-11-16 17:24 UTC, merged